version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/chat_history.db:/app/chat_history.db
    env_file:
      - ./backend/.env
    ports:
      - "8003:8003"
    restart: unless-stopped

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8004:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
